# Generated by Django 5.0.2 on 2024-05-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_management', '0003_event_likes_count_event_price_event_type_like_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_amount',
            field=models.BigIntegerField(default=100),
        ),
    ]
