# Generated by Django 5.0.2 on 2024-05-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_management', '0005_alter_ticket_event_alter_ticket_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
